#!/bin/bash
#if [[ ! -d  /opt/jdk-14.0.2 ]]; then
#  curl -O https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz
#  tar xvf openjdk-14.0.2_linux-x64_bin.tar.gz
#  rm -rf openjdk-14.0.2_linux-x64_bin.tar.gz
#  mv jdk-14.0.2 /opt/
#  ln -s /opt/jdk-14.0.2 /opt/jdk
#fi


