apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: busybox
    image: registry.pellep.io:5000/busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
