# syntax=docker/dockerfile:experimental
FROM ubuntu:20.04 as nvim-builder

RUN --mount=type=bind,source=scripts,target=/scripts \
     CMAKE_INSTALL_PREFIX=/build /scripts/build-nvim-linux.sh build

FROM ubuntu:20.10

COPY --from=nvim-builder /build/ /usr/local

RUN --mount=type=bind,source=scripts,target=/scripts \
    scripts/install-ubuntu-packages.sh && \
    scripts/install-go-linux.sh && \
    scripts/install-devops-ubuntu.sh && \
    scripts/install-rust-linux.sh && \
    curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin/ && \
	  groupadd -g 1000 devops && \
	  useradd -u 1000 --create-home --gid devops devops && \
	  usermod -a -G sudo devops && \
	  echo "devops  ALL=(ALL)  NOPASSWD:ALL" > /etc/sudoers.d/devops

ENV CONTAINER=docker

WORKDIR /home/devops
USER devops
COPY ./dotfiles /home/devops/.dotfiles


RUN /home/devops/.dotfiles/bootstrap.sh

CMD ["/bin/zsh"]
