# syntax=docker/dockerfile:experimental
FROM ubuntu:20.04 as nvim-builder

RUN --mount=type=bind,source=scripts,target=/scripts \
     CMAKE_INSTALL_PREFIX=/build /scripts/build-nvim-linux.sh build


FROM fedora:34

COPY --from=nvim-builder /build/ /usr/local

RUN --mount=type=bind,source=scripts,target=/scripts \
    scripts/install-fedora-packages.sh && \
    scripts/install-go-linux.sh && \
	  groupadd -g 1000 devops && \
	  useradd -u 1000 --create-home --gid devops devops && \
	  echo "devops  ALL=(ALL)  NOPASSWD:ALL" > /etc/sudoers.d/devops


WORKDIR /home/devops

RUN chmod 777 /tmp
USER devops
ENV GOPATH /home/devops/go
ENV GOBIN /home/devops/go/bin
COPY ./dotfiles /home/devops/.dotfiles

RUN /home/devops/.dotfiles/bootstrap.sh

CMD ["/bin/zsh"]

